version: '3.8'

services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    #environment : 
    #- RABBITMQ_DEFAULT_USER=user
    #- RABBITMQ_DEFAULT_PASS=password

  server:
    build: serverjs
    volumes:
      - ./serverjs:/app
    ports:
      - 5001:5000
    depends_on:
      - rabbitmq

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1

  worker2:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
