version: '3.8'

services:
  server:
    build: serverjs
    volumes:
      - ./serverjs:/app
    ports:
      - 5001:5000

  worker:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1

  worker2:
    build: worker
    volumes:
      - ./worker:/app
    environment:
      - PYTHONUNBUFFERED=1
